Update __init__.py
Updated to fix the following error when loading sensors:

"home-assistant/homeassistant/components/sensor/__init__.py", line 87, in setup
    hass.track_time_change(update_sensor_states, seconds=range(0, 60, 3))
TypeError: track_time_change() got an unexpected keyword argument 'seconds'"

the named parameter was using seconds instead of second